/*
const { createPool } = require("mysql2");

const pool = createPool({
  host: "localhost",
  user: "Madidev",
  password: "#$@asd1w32523!D",
  connectionLimit: 200000,
  database: "lol_akinator_clone",
});

pool.query(`select * from champion_objects`, (err, res) => {
  return console.dir(res, { maxArrayLength: null });
});
*/

// result from console.dir
export { championDatabase };
const championDatabase = [
  {
    Name: "Aatrox",
    Key_region: "Shurima",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Top",
    Typical_lane_two: "None",
    Class: "Bruiser",
    Resource_type: "None",
    Race: "Darkin",
    Faction: "the Darkin",
    Key_Character_rel: "Pantheon",
  },
  {
    Name: "Ahri",
    Key_region: "Ionia",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Mid",
    Typical_lane_two: "None",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Vastaya",
    Faction: "the Vastaya",
    Key_Character_rel: "Yasuo",
  },
  {
    Name: "Akali",
    Key_region: "Ionia",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Mid",
    Typical_lane_two: "Top",
    Class: "Assassin",
    Resource_type: "Energy",
    Race: "Human",
    Faction: "the Kinkou Order",
    Key_Character_rel: "Shen",
  },
  {
    Name: "Akshan",
    Key_region: "Shurima",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Mid",
    Typical_lane_two: "Top",
    Class: "Marksman",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Sentinels of Light",
    Key_Character_rel: "Viego",
  },
  {
    Name: "Alistar",
    Key_region: "Noxus",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Support",
    Typical_lane_two: "None",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Minotaur",
    Faction: "the Reckoners",
    Key_Character_rel: "Sett",
  },
  {
    Name: "Amumu",
    Key_region: "Shurima",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Jungle",
    Typical_lane_two: "Support",
    Class: "Tank",
    Resource_type: "Mana",
    Race: "Yordle",
    Faction: "None",
    Key_Character_rel: "None",
  },
  {
    Name: "Anivia",
    Key_region: "the Freljord",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Mid",
    Typical_lane_two: "None",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Spirit God",
    Faction: "the Avarosan",
    Key_Character_rel: "Ashe",
  },
  {
    Name: "Annie",
    Key_region: "Noxus",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Mid",
    Typical_lane_two: "Support",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "None",
    Key_Character_rel: "LeBlanc",
  },
  {
    Name: "Aphelios",
    Key_region: "Targon",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Bottom",
    Typical_lane_two: "None",
    Class: "Marksman",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Lunari",
    Key_Character_rel: "Diana",
  },
  {
    Name: "Ashe",
    Key_region: "the Freljord",
    Adaptive_type: "physical",
    Sex: "female",
    Typical_lane: "Bottom",
    Typical_lane_two: "Support",
    Class: "Marksman",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Avarosan",
    Key_Character_rel: "Tryndamere",
  },
  {
    Name: "Aurelion Sol",
    Key_region: "Targon",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Mid",
    Typical_lane_two: "None",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Celestial",
    Faction: "None",
    Key_Character_rel: "Pantheon",
  },
  {
    Name: "Azir",
    Key_region: "Shurima",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Mid",
    Typical_lane_two: "None",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Ascendant",
    Faction: "the Shuriman Empire",
    Key_Character_rel: "Xerath",
  },
  {
    Name: "Bard",
    Key_region: "Unknown",
    Adaptive_type: "magical",
    Sex: "N",
    Typical_lane: "Support",
    Typical_lane_two: "None",
    Class: "Support",
    Resource_type: "Mana",
    Race: "Celestial",
    Faction: "None",
    Key_Character_rel: "Aurelion Sol",
  },
  {
    Name: "Bel'Veth",
    Key_region: "the Void",
    Adaptive_type: "physical",
    Sex: "female",
    Typical_lane: "Jungle",
    Typical_lane_two: "None",
    Class: "Fighter",
    Resource_type: "None",
    Race: "Voidborn",
    Faction: "the Void",
    Key_Character_rel: "Kai'Sa",
  },
  {
    Name: "Blitzcrank",
    Key_region: "Zaun",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Support",
    Typical_lane_two: "None",
    Class: "Support",
    Resource_type: "Mana",
    Race: "Golem",
    Faction: "None",
    Key_Character_rel: "Viktor",
  },
  {
    Name: "Brand",
    Key_region: "the Freljord",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Support",
    Typical_lane_two: "Mid",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "None",
    Key_Character_rel: "Ryze",
  },
  {
    Name: "Braum",
    Key_region: "the Freljord",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Support",
    Typical_lane_two: "None",
    Class: "Tank",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Avarosan",
    Key_Character_rel: "Ashe",
  },
  {
    Name: "Caitlyn",
    Key_region: "Piltover",
    Adaptive_type: "physical",
    Sex: "female",
    Typical_lane: "Bottom",
    Typical_lane_two: "None",
    Class: "Marksman",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Piltover Wardens",
    Key_Character_rel: "Vi",
  },
  {
    Name: "Camille",
    Key_region: "Piltover",
    Adaptive_type: "physical",
    Sex: "female",
    Typical_lane: "Top",
    Typical_lane_two: "Mid",
    Class: "Fighter",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Ferros Clan",
    Key_Character_rel: "Viktor",
  },
  {
    Name: "Cassiopeia",
    Key_region: "Noxus",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Mid",
    Typical_lane_two: "Bottom",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Du Couteau House",
    Key_Character_rel: "Katarina",
  },
  {
    Name: "Cho'Gath",
    Key_region: "the Void",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Top",
    Typical_lane_two: "Mid",
    Class: "Tank",
    Resource_type: "Mana",
    Race: "Voidborn",
    Faction: "the Void",
    Key_Character_rel: "Vel'Koz",
  },
  {
    Name: "Corki",
    Key_region: "Bandle City",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Mid",
    Typical_lane_two: "Bottom",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Yordle",
    Faction: "the Yipsnakes",
    Key_Character_rel: "Teemo",
  },
  {
    Name: "Darius",
    Key_region: "Noxus",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Top",
    Typical_lane_two: "None",
    Class: "Fighter",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Trifarian Legion",
    Key_Character_rel: "Draven",
  },
  {
    Name: "Diana",
    Key_region: "Targon",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Jungle",
    Typical_lane_two: "Mid",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Aspect Host",
    Faction: "the Lunari",
    Key_Character_rel: "Leona",
  },
  {
    Name: "Dr. Mundo",
    Key_region: "Zaun",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Top",
    Typical_lane_two: "Jungle",
    Class: "Tank",
    Resource_type: "Health",
    Race: "Human",
    Faction: "None",
    Key_Character_rel: "Ekko",
  },
  {
    Name: "Draven",
    Key_region: "Noxus",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Bottom",
    Typical_lane_two: "None",
    Class: "Marksman",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Reckoners",
    Key_Character_rel: "Darius",
  },
  {
    Name: "Ekko",
    Key_region: "Zaun",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Mid",
    Typical_lane_two: "Jungle",
    Class: "Assassin",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Sumpsnipe",
    Key_Character_rel: "Vi",
  },
  {
    Name: "Elise",
    Key_region: "Noxus",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Jungle",
    Typical_lane_two: "None",
    Class: "Assassin",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Black Rose",
    Key_Character_rel: "LeBlanc",
  },
  {
    Name: "Evelynn",
    Key_region: "Unknown",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Jungle",
    Typical_lane_two: "None",
    Class: "Assassin",
    Resource_type: "Mana",
    Race: "Demon",
    Faction: "None",
    Key_Character_rel: "Fiddlesticks",
  },
  {
    Name: "Ezreal",
    Key_region: "Piltover",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Bottom",
    Typical_lane_two: "Mid",
    Class: "Marksman",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "None",
    Key_Character_rel: "Kassadin",
  },
  {
    Name: "Fiddlesticks",
    Key_region: "Unknown",
    Adaptive_type: "magical",
    Sex: "N",
    Typical_lane: "Jungle",
    Typical_lane_two: "None",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Demon",
    Faction: "None",
    Key_Character_rel: "Evelynn",
  },
  {
    Name: "Fiora",
    Key_region: "Demacia",
    Adaptive_type: "physical",
    Sex: "female",
    Typical_lane: "Top",
    Typical_lane_two: "None",
    Class: "Fighter",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Laurent House",
    Key_Character_rel: "Garen",
  },
  {
    Name: "Fizz",
    Key_region: "Bandle City",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Mid",
    Typical_lane_two: "Top",
    Class: "Assassin",
    Resource_type: "Mana",
    Race: "Yordle",
    Faction: "None",
    Key_Character_rel: "Nami",
  },
  {
    Name: "Galio",
    Key_region: "Demacia",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Mid",
    Typical_lane_two: "Suppor",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Golem",
    Faction: "the Durand House",
    Key_Character_rel: "Poppy",
  },
  {
    Name: "Gangplank",
    Key_region: "Bilgewater",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Top",
    Typical_lane_two: "Mid",
    Class: "Fighter",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Jagged Hooks",
    Key_Character_rel: "Illaoi",
  },
  {
    Name: "Garen",
    Key_region: "Demacia",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Top",
    Typical_lane_two: "Mid",
    Class: "Fighter",
    Resource_type: "None",
    Race: "Human",
    Faction: "the Dauntless Vanguard",
    Key_Character_rel: "Lux",
  },
  {
    Name: "Gnar",
    Key_region: "the Freljord",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Top",
    Typical_lane_two: "Mid",
    Class: "Fighter",
    Resource_type: "Rage",
    Race: "Yordle",
    Faction: "None",
    Key_Character_rel: "Rengar",
  },
  {
    Name: "Gragas",
    Key_region: "the Freljord",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Top",
    Typical_lane_two: "Mid",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Avarosan",
    Key_Character_rel: "Tryndamere",
  },
  {
    Name: "Graves",
    Key_region: "Bilgewater",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Jungle",
    Typical_lane_two: "None",
    Class: "Marksman",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Sentinels of Light",
    Key_Character_rel: "Twisted Fate",
  },
  {
    Name: "Gwen",
    Key_region: "Shadow Isles",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Top",
    Typical_lane_two: "Mid",
    Class: "Fighter",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Sentinels of Light",
    Key_Character_rel: "Isolde",
  },
  {
    Name: "Hecarim",
    Key_region: "Shadow Isles",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Jungle",
    Typical_lane_two: "Top",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Wraith",
    Faction: "the Black Mist Vanguard",
    Key_Character_rel: "Kalista",
  },
  {
    Name: "Heimerdinger",
    Key_region: "Bandle City",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Mid",
    Typical_lane_two: "Top",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Yordle",
    Faction: "None",
    Key_Character_rel: "Jayce",
  },
  {
    Name: "Illaoi",
    Key_region: "Bilgewater",
    Adaptive_type: "physical",
    Sex: "female",
    Typical_lane: "Top",
    Typical_lane_two: "None",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Buhru",
    Key_Character_rel: "Gangplank",
  },
  {
    Name: "Irelia",
    Key_region: "Ionia",
    Adaptive_type: "physical",
    Sex: "female",
    Typical_lane: "Top",
    Typical_lane_two: "Mid",
    Class: "Fighter",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Sentinels of Light",
    Key_Character_rel: "Swain",
  },
  {
    Name: "Ivern",
    Key_region: "the Freljord",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Jungle",
    Typical_lane_two: "None",
    Class: "Support",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "None",
    Key_Character_rel: "Lissandra",
  },
  {
    Name: "Janna",
    Key_region: "Zaun",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Support",
    Typical_lane_two: "None",
    Class: "Support",
    Resource_type: "Mana",
    Race: "Spirit God",
    Faction: "None",
    Key_Character_rel: "Ekko",
  },
  {
    Name: "Jarvan IV",
    Key_region: "Demacia",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Jungle",
    Typical_lane_two: "None",
    Class: "Fighter",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Lightshield House",
    Key_Character_rel: "Shyvana",
  },
  {
    Name: "Jax",
    Key_region: "Icathia",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Top",
    Typical_lane_two: "Jungle",
    Class: "Fighter",
    Resource_type: "Mana",
    Race: "Unknown",
    Faction: "None",
    Key_Character_rel: "Fiora",
  },
  {
    Name: "Jayce",
    Key_region: "Piltover",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Top",
    Typical_lane_two: "Mid",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Ferros Clan",
    Key_Character_rel: "Viktor",
  },
  {
    Name: "Jhin",
    Key_region: "Ionia",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Bottom",
    Typical_lane_two: "None",
    Class: "Marksman",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "None",
    Key_Character_rel: "Zed",
  },
  {
    Name: "Jinx",
    Key_region: "Zaun",
    Adaptive_type: "physical",
    Sex: "female",
    Typical_lane: "Bottom",
    Typical_lane_two: "None",
    Class: "Marksman",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "None",
    Key_Character_rel: "Vi",
  },
  {
    Name: "Kai'Sa",
    Key_region: "Shurima",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Bottom",
    Typical_lane_two: "None",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "The Preservers of Valoran",
    Key_Character_rel: "Kassadin",
  },
  {
    Name: "Kalista",
    Key_region: "Shadow Isles",
    Adaptive_type: "physical",
    Sex: "female",
    Typical_lane: "Bottom",
    Typical_lane_two: "None",
    Class: "Marksman",
    Resource_type: "Mana",
    Race: "Wrath",
    Faction: "None",
    Key_Character_rel: "Hecarim",
  },
  {
    Name: "Karma",
    Key_region: "Ionia",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Support",
    Typical_lane_two: "Mid",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "None",
    Key_Character_rel: "Irelia",
  },
  {
    Name: "Karthus",
    Key_region: "Shadow Isles",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Jungle",
    Typical_lane_two: "Mid",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Wraith",
    Faction: "None",
    Key_Character_rel: "Thresh",
  },
  {
    Name: "Kassadin",
    Key_region: "the Void",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Mid",
    Typical_lane_two: "None",
    Class: "Assassin",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "The Preservers of Valoran",
    Key_Character_rel: "Kai'Sa",
  },
  {
    Name: "Katarina",
    Key_region: "Noxus",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Mid",
    Typical_lane_two: "None",
    Class: "Multi-class",
    Resource_type: "None",
    Race: "Human",
    Faction: "the Du Couteau House",
    Key_Character_rel: "Cassiopeia",
  },
  {
    Name: "Kayle",
    Key_region: "Demacia",
    Adaptive_type: "physical",
    Sex: "female",
    Typical_lane: "Top",
    Typical_lane_two: "Mid",
    Class: "Fighter",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "None",
    Key_Character_rel: "Morgana",
  },
  {
    Name: "Kayn",
    Key_region: "Noxus",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Jungle",
    Typical_lane_two: "None",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Shadow Order",
    Key_Character_rel: "Zed",
  },
  {
    Name: "Kennen",
    Key_region: "Bandle City",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Top",
    Typical_lane_two: "Mid",
    Class: "Multi-class",
    Resource_type: "Energy",
    Race: "Yordle",
    Faction: "the Kinkou Order",
    Key_Character_rel: "Shen",
  },
  {
    Name: "Kha'Zix",
    Key_region: "the Void",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Jungle",
    Typical_lane_two: "None",
    Class: "Assassin",
    Resource_type: "Mana",
    Race: "Voidborn",
    Faction: "the Void",
    Key_Character_rel: "Rengar",
  },
  {
    Name: "Kindred",
    Key_region: "Unknown",
    Adaptive_type: "physical",
    Sex: "N",
    Typical_lane: "Jungle",
    Typical_lane_two: "None",
    Class: "Marksman",
    Resource_type: "Mana",
    Race: "Spirit God",
    Faction: "None",
    Key_Character_rel: "Mordekaiser",
  },
  {
    Name: "Kled",
    Key_region: "Bandle City",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Top",
    Typical_lane_two: "Jungle",
    Class: "Fighter",
    Resource_type: "Courage",
    Race: "Yordle",
    Faction: "the Trifarian Legion",
    Key_Character_rel: "Darius",
  },
  {
    Name: "Kog'Maw",
    Key_region: "the Void",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Bottom",
    Typical_lane_two: "Mid",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Voidborn",
    Faction: "the Void",
    Key_Character_rel: "Kha'Zix",
  },
  {
    Name: "Le'Blanc",
    Key_region: "Noxus",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Mid",
    Typical_lane_two: "None",
    Class: "Assassin",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Black Rose",
    Key_Character_rel: "Swain",
  },
  {
    Name: "Lee'Sin",
    Key_region: "Ionia",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Jungle",
    Typical_lane_two: "None",
    Class: "Multi-class",
    Resource_type: "Energy",
    Race: "Human",
    Faction: "the Shojin Order",
    Key_Character_rel: "Udyr",
  },
  {
    Name: "Leona",
    Key_region: "Targon",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Support",
    Typical_lane_two: "None",
    Class: "Support",
    Resource_type: "Mana",
    Race: "Aspect Host",
    Faction: "the Solari",
    Key_Character_rel: "Diana",
  },
  {
    Name: "Lillia",
    Key_region: "Ionia",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Jungle",
    Typical_lane_two: "Top",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Fae Fawn",
    Faction: "None",
    Key_Character_rel: "Yone",
  },
  {
    Name: "Lissandra",
    Key_region: "the Freljord",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Mid",
    Typical_lane_two: "Top",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Frostguard",
    Key_Character_rel: "Trundle",
  },
  {
    Name: "Lucian",
    Key_region: "Demacia",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Bottom",
    Typical_lane_two: "Mid",
    Class: "Marksman",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Sentinels of Light",
    Key_Character_rel: "Senna",
  },
  {
    Name: "Lulu",
    Key_region: "Bandle City",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Support",
    Typical_lane_two: "Top",
    Class: "Support",
    Resource_type: "Mana",
    Race: "Yordle",
    Faction: "None",
    Key_Character_rel: "Teemo",
  },
  {
    Name: "Lux",
    Key_region: "Demacia",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Support",
    Typical_lane_two: "Mid",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Crownguard House",
    Key_Character_rel: "Sylas",
  },
  {
    Name: "Malphite",
    Key_region: "Ixtal",
    Adaptive_type: "magical",
    Sex: "N",
    Typical_lane: "Top",
    Typical_lane_two: "Mid",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Golem",
    Faction: "None",
    Key_Character_rel: "Taliyah",
  },
  {
    Name: "Malzahar",
    Key_region: "Icathia",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Mid",
    Typical_lane_two: "None",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "The Cult of the Void",
    Key_Character_rel: "Kassadin",
  },
  {
    Name: "Maokai",
    Key_region: "Shadow Isles",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Top",
    Typical_lane_two: "Support",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Treant",
    Faction: "None",
    Key_Character_rel: "Zyra",
  },
  {
    Name: "Master Yi",
    Key_region: "Ionia",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Jungle",
    Typical_lane_two: "None",
    Class: "Fighter",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Wuju Order",
    Key_Character_rel: "Wukong",
  },
  {
    Name: "Miss Fortune",
    Key_region: "Bilgewater",
    Adaptive_type: "physical",
    Sex: "female",
    Typical_lane: "Bottom",
    Typical_lane_two: "None",
    Class: "Marksman",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Syrens",
    Key_Character_rel: "Gangplank",
  },
  {
    Name: "Mordekaiser",
    Key_region: "Noxus",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Top",
    Typical_lane_two: "Jungle",
    Class: "Fighter",
    Resource_type: "Shield",
    Race: "Deceased",
    Faction: "the Iron Revenant",
    Key_Character_rel: "LeBlanc",
  },
  {
    Name: "Morgana",
    Key_region: "Demacia",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Support",
    Typical_lane_two: "Mid",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "None",
    Key_Character_rel: "Kayle",
  },
  {
    Name: "Nami",
    Key_region: "N",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Support",
    Typical_lane_two: "None",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Vastaya",
    Faction: "the Vastaya",
    Key_Character_rel: "Fizz",
  },
  {
    Name: "Nasus",
    Key_region: "Shurima",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Top",
    Typical_lane_two: "Jungle",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Ascendant",
    Faction: "None",
    Key_Character_rel: "Renekton",
  },
  {
    Name: "Nautilus",
    Key_region: "Bilgewater",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Support",
    Typical_lane_two: "Top",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Revenant",
    Faction: "None",
    Key_Character_rel: "Fizz",
  },
  {
    Name: "Neeko",
    Key_region: "Ixtal",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Middle",
    Typical_lane_two: "Support",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Oovi-kat",
    Faction: "the Vastaya",
    Key_Character_rel: "Nidalee",
  },
  {
    Name: "Nidalee",
    Key_region: "Ixtal",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Jungle",
    Typical_lane_two: "Support",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "None",
    Key_Character_rel: "Neeko",
  },
  {
    Name: "Nilah",
    Key_region: "Bilgewater",
    Adaptive_type: "physical",
    Sex: "female",
    Typical_lane: "Bottom",
    Typical_lane_two: "None",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "None",
    Key_Character_rel: "Graves",
  },
  {
    Name: "Nocturne",
    Key_region: "Unknown",
    Adaptive_type: "physical",
    Sex: "N",
    Typical_lane: "Jungle",
    Typical_lane_two: "Top",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Demon",
    Faction: "None",
    Key_Character_rel: "Fiddlesticks",
  },
  {
    Name: "Nunu and Willump",
    Key_region: "the Freljord",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Jungle",
    Typical_lane_two: "Mid",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Frostguard",
    Key_Character_rel: "Lissandra",
  },
  {
    Name: "Olaf",
    Key_region: "the Freljord",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Jungle",
    Typical_lane_two: "Top",
    Class: "Fighter",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Winter's Claw",
    Key_Character_rel: "Sejuani",
  },
  {
    Name: "Orianna",
    Key_region: "Piltover",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Mid",
    Typical_lane_two: "None",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Golem",
    Faction: "None",
    Key_Character_rel: "Blitzcrank",
  },
  {
    Name: "Ornn",
    Key_region: "the Freljord",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Top",
    Typical_lane_two: "None",
    Class: "Tank",
    Resource_type: "Mana",
    Race: "Spirit God",
    Faction: "None",
    Key_Character_rel: "Volibear",
  },
  {
    Name: "Pantheon",
    Key_region: "Targon",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Top",
    Typical_lane_two: "Support",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Rakkor",
    Key_Character_rel: "Aatrox",
  },
  {
    Name: "Poppy",
    Key_region: "Bandle City",
    Adaptive_type: "physical",
    Sex: "female",
    Typical_lane: "Top",
    Typical_lane_two: "Jungle",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Yordle",
    Faction: "None",
    Key_Character_rel: "Galio",
  },
  {
    Name: "Pyke",
    Key_region: "Bilgewater",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Support",
    Typical_lane_two: "Mid",
    Class: "Assassin",
    Resource_type: "Mana",
    Race: "Revenant",
    Faction: "the Sentinels of Light",
    Key_Character_rel: "Graves",
  },
  {
    Name: "Qiyana",
    Key_region: "Ixtal",
    Adaptive_type: "physical",
    Sex: "female",
    Typical_lane: "Mid",
    Typical_lane_two: "Jungle",
    Class: "Assassin",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "None",
    Key_Character_rel: "Malphite",
  },
  {
    Name: "Quinn",
    Key_region: "Demacia",
    Adaptive_type: "physical",
    Sex: "female",
    Typical_lane: "Top",
    Typical_lane_two: "None",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Demacian Rangers",
    Key_Character_rel: "Jarvan IV",
  },
  {
    Name: "Rakan",
    Key_region: "Ionia",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Support",
    Typical_lane_two: "Mid",
    Class: "Support",
    Resource_type: "Mana",
    Race: "Vastaya",
    Faction: "the Vastaya",
    Key_Character_rel: "Xayah",
  },
  {
    Name: "Rammus",
    Key_region: "Shurima",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Jungle",
    Typical_lane_two: "None",
    Class: "Tank",
    Resource_type: "Mana",
    Race: "Unknown",
    Faction: "None",
    Key_Character_rel: "None",
  },
  {
    Name: "Rek'Sai",
    Key_region: "the Void",
    Adaptive_type: "physical",
    Sex: "female",
    Typical_lane: "Jungle",
    Typical_lane_two: "None",
    Class: "Fighter",
    Resource_type: "Rage",
    Race: "Voidborn",
    Faction: "None",
    Key_Character_rel: "Skarner",
  },
  {
    Name: "Rell",
    Key_region: "Noxus",
    Adaptive_type: "magic",
    Sex: "female",
    Typical_lane: "Support",
    Typical_lane_two: "None",
    Class: "Support",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "None",
    Key_Character_rel: "LeBlanc",
  },
  {
    Name: "Renata Glasc",
    Key_region: "Zaun",
    Adaptive_type: "magic",
    Sex: "female",
    Typical_lane: "Support",
    Typical_lane_two: "None",
    Class: "Support",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Glasc Industries",
    Key_Character_rel: "Zeri",
  },
  {
    Name: "Renekton",
    Key_region: "Shurima",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Top",
    Typical_lane_two: "Mid",
    Class: "Fighter",
    Resource_type: "Fury",
    Race: "Ascendant",
    Faction: "None",
    Key_Character_rel: "Nasus",
  },
  {
    Name: "Rengar",
    Key_region: "Ixtal",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Jungle",
    Typical_lane_two: "Top",
    Class: "Assassin",
    Resource_type: "Ferocity",
    Race: "Vastaya",
    Faction: "the Sentinels of Light",
    Key_Character_rel: "Kha'Zix",
  },
  {
    Name: "Riven",
    Key_region: "Noxus",
    Adaptive_type: "physical",
    Sex: "female",
    Typical_lane: "Top",
    Typical_lane_two: "None",
    Class: "Fighter",
    Resource_type: "None",
    Race: "Human",
    Faction: "the Reckoners",
    Key_Character_rel: "Yasuo",
  },
  {
    Name: "Rumble",
    Key_region: "Bandle City",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Top",
    Typical_lane_two: "Mid",
    Class: "Mage",
    Resource_type: "Heat",
    Race: "Yordle",
    Faction: "None",
    Key_Character_rel: "Tristana",
  },
  {
    Name: "Ryze",
    Key_region: "Unknown",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Mid",
    Typical_lane_two: "Top",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "None",
    Key_Character_rel: "Brand",
  },
  {
    Name: "Samira",
    Key_region: "Noxus",
    Adaptive_type: "physical",
    Sex: "female",
    Typical_lane: "Bottom",
    Typical_lane_two: "None",
    Class: "Marksman",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "None",
    Key_Character_rel: "LeBlanc",
  },
  {
    Name: "Sejuani",
    Key_region: "the Freljord",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Jungle",
    Typical_lane_two: "Top",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Winter's Claw",
    Key_Character_rel: "Olaf",
  },
  {
    Name: "Senna",
    Key_region: "Shadow Isles",
    Adaptive_type: "physical",
    Sex: "female",
    Typical_lane: "Bottom",
    Typical_lane_two: "None",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Sentinels of Light",
    Key_Character_rel: "Lucian",
  },
  {
    Name: "Seraphine",
    Key_region: "Piltover",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Support",
    Typical_lane_two: "Mid",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "None",
    Key_Character_rel: "Skarner",
  },
  {
    Name: "Sett",
    Key_region: "Ionia",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Top",
    Typical_lane_two: "Support",
    Class: "Fighter",
    Resource_type: "Grit",
    Race: "Vastaya",
    Faction: "the Vastaya",
    Key_Character_rel: "Draven",
  },
  {
    Name: "Shaco",
    Key_region: "Unknown",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Jungle",
    Typical_lane_two: "Support",
    Class: "Assassin",
    Resource_type: "Mana",
    Race: "Spirit",
    Faction: "None",
    Key_Character_rel: "Fiddlesticks",
  },
  {
    Name: "Shen",
    Key_region: "Ionia",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Top",
    Typical_lane_two: "Support",
    Class: "Tank",
    Resource_type: "Energy",
    Race: "Human",
    Faction: "the Kinkou Order",
    Key_Character_rel: "Zed",
  },
  {
    Name: "Shyvana",
    Key_region: "Demacia",
    Adaptive_type: "physical",
    Sex: "female",
    Typical_lane: "Jungle",
    Typical_lane_two: "Top",
    Class: "Multi-class",
    Resource_type: "Fury",
    Race: "Dragon",
    Faction: "the Dragonguard",
    Key_Character_rel: "Jarvan IV",
  },
  {
    Name: "Singed",
    Key_region: "Zaun",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Top",
    Typical_lane_two: "None",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "None",
    Key_Character_rel: "Warwick",
  },
  {
    Name: "Sion",
    Key_region: "Noxus",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Top",
    Typical_lane_two: "None",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Revenant",
    Faction: "None",
    Key_Character_rel: "Jarvan IV",
  },
  {
    Name: "Sivir",
    Key_region: "Shurima",
    Adaptive_type: "physical",
    Sex: "female",
    Typical_lane: "Bottom",
    Typical_lane_two: "None",
    Class: "Marksman",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "None",
    Key_Character_rel: "Azir",
  },
  {
    Name: "Skarner",
    Key_region: "Shurima",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Jungle",
    Typical_lane_two: "Top",
    Class: "Fighter",
    Resource_type: "Mana",
    Race: "Brackern",
    Faction: "the Brackern",
    Key_Character_rel: "Seraphine",
  },
  {
    Name: "Sona",
    Key_region: "Demacia",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Support",
    Typical_lane_two: "None",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Buvelle House",
    Key_Character_rel: "Ryze",
  },
  {
    Name: "Soraka",
    Key_region: "Targon",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Support",
    Typical_lane_two: "None",
    Class: "Support",
    Resource_type: "Mana",
    Race: "Celestial",
    Faction: "None",
    Key_Character_rel: "Bard",
  },
  {
    Name: "Swain",
    Key_region: "Noxus",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Support",
    Typical_lane_two: "Mid",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Swain House",
    Key_Character_rel: "Katarina",
  },
  {
    Name: "Sylas",
    Key_region: "Demacia",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Mid",
    Typical_lane_two: "Top",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Winter's Claw",
    Key_Character_rel: "Lux",
  },
  {
    Name: "Syndra",
    Key_region: "Ionia",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Mid",
    Typical_lane_two: "Bottom",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "None",
    Key_Character_rel: "Irelia",
  },
  {
    Name: "Tahm Kench",
    Key_region: "Bilgewater",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Top",
    Typical_lane_two: "Support",
    Class: "Tank",
    Resource_type: "Mana",
    Race: "Demon",
    Faction: "None",
    Key_Character_rel: "Fiddlesticks",
  },
  {
    Name: "Taliyah",
    Key_region: "Shurima",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Mid",
    Typical_lane_two: "Jungle",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "None",
    Key_Character_rel: "Yasuo",
  },
  {
    Name: "Talon",
    Key_region: "Noxus",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Mid",
    Typical_lane_two: "None",
    Class: "Assassin",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Du Couteau House",
    Key_Character_rel: "Katarina",
  },
  {
    Name: "Taric",
    Key_region: "Targon",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Support",
    Typical_lane_two: "Jungle",
    Class: "Support",
    Resource_type: "Mana",
    Race: "Aspect Host",
    Faction: "the Dauntless Vanguard",
    Key_Character_rel: "Zoe",
  },
  {
    Name: "Teemo",
    Key_region: "Bandle City",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Top",
    Typical_lane_two: "None",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Yordle",
    Faction: "None",
    Key_Character_rel: "Tristana",
  },
  {
    Name: "Thresh",
    Key_region: "Shadow Isles",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Support",
    Typical_lane_two: "None",
    Class: "Support",
    Resource_type: "Mana",
    Race: "Wraith",
    Faction: "None",
    Key_Character_rel: "Lucian",
  },
  {
    Name: "Tristana",
    Key_region: "Bandle City",
    Adaptive_type: "physical",
    Sex: "female",
    Typical_lane: "Bottom",
    Typical_lane_two: "Mid",
    Class: "Marksman",
    Resource_type: "Mana",
    Race: "Yordle",
    Faction: "None",
    Key_Character_rel: "Teemo",
  },
  {
    Name: "Trundle",
    Key_region: "the Freljord",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Jungle",
    Typical_lane_two: "Top",
    Class: "Fighter",
    Resource_type: "Mana",
    Race: "Troll",
    Faction: "the Frostguard",
    Key_Character_rel: "Lissandra",
  },
  {
    Name: "Tryndamere",
    Key_region: "the Freljord",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Top",
    Typical_lane_two: "None",
    Class: "Fighter",
    Resource_type: "Fury",
    Race: "Human",
    Faction: "the Avarosan",
    Key_Character_rel: "Aatrox",
  },
  {
    Name: "Twisted Fate",
    Key_region: "Bilgewater",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Mid",
    Typical_lane_two: "None",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "None",
    Key_Character_rel: "Graves",
  },
  {
    Name: "Twitch",
    Key_region: "Zaun",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Bottom",
    Typical_lane_two: "Jungle",
    Class: "Marksman",
    Resource_type: "Mana",
    Race: "Plague Rat",
    Faction: "None",
    Key_Character_rel: "Zac",
  },
  {
    Name: "Udyr",
    Key_region: "the Freljord",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Jungle",
    Typical_lane_two: "Top",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Winter's Claw",
    Key_Character_rel: "Lee Sin",
  },
  {
    Name: "Urgot",
    Key_region: "Zaun",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Top",
    Typical_lane_two: "None",
    Class: "Fighter",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "None",
    Key_Character_rel: "Caitlyn",
  },
  {
    Name: "Varus",
    Key_region: "Ionia",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Bottom",
    Typical_lane_two: "None",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Darkin",
    Faction: "the Darkin",
    Key_Character_rel: "Kayn",
  },
  {
    Name: "Vayne",
    Key_region: "Demacia",
    Adaptive_type: "physical",
    Sex: "female",
    Typical_lane: "Bottom",
    Typical_lane_two: "Top",
    Class: "Marksman",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Sentinels of Light",
    Key_Character_rel: "Evelynn",
  },
  {
    Name: "Veigar",
    Key_region: "Bandle City",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Mid",
    Typical_lane_two: "Bottom",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Yordle",
    Faction: "None",
    Key_Character_rel: "Lulu",
  },
  {
    Name: "Vel'Koz",
    Key_region: "the Void",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Mid",
    Typical_lane_two: "Support",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Voidborn",
    Faction: "the Void",
    Key_Character_rel: "Kha'Zix",
  },
  {
    Name: "Vex",
    Key_region: "Bandle City",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Mid",
    Typical_lane_two: "None",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Yordle",
    Faction: "None",
    Key_Character_rel: "Viego",
  },
  {
    Name: "Vi",
    Key_region: "Piltover",
    Adaptive_type: "physical",
    Sex: "female",
    Typical_lane: "Jungle",
    Typical_lane_two: "None",
    Class: "Fighter",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Piltover Wardens",
    Key_Character_rel: "Jinx",
  },
  {
    Name: "Viego",
    Key_region: "Shadow Isles",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Jungle",
    Typical_lane_two: "None",
    Class: "Fighter",
    Resource_type: "None",
    Race: "Wraith",
    Faction: "None",
    Key_Character_rel: "Kalista",
  },
  {
    Name: "Viktor",
    Key_region: "Zaun",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Mid",
    Typical_lane_two: "None",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "None",
    Key_Character_rel: "Jayce",
  },
  {
    Name: "Vladimir",
    Key_region: "Noxus",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Mid",
    Typical_lane_two: "Top",
    Class: "Mage",
    Resource_type: "Bloodthirst",
    Race: "Human",
    Faction: "the Black Rose",
    Key_Character_rel: "Viego",
  },
  {
    Name: "Volibear",
    Key_region: "the Freljord",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Top",
    Typical_lane_two: "Jungle",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Spirit God",
    Faction: "the Ursine",
    Key_Character_rel: "Ornn",
  },
  {
    Name: "Warwick",
    Key_region: "Zaun",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Jungle",
    Typical_lane_two: "Top",
    Class: "Fighter",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "None",
    Key_Character_rel: "Singed",
  },
  {
    Name: "Wukong",
    Key_region: "Ionia",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Top",
    Typical_lane_two: "Jungle",
    Class: "Fighter",
    Resource_type: "Mana",
    Race: "Vastaya",
    Faction: "the Wuju Order",
    Key_Character_rel: "Master Yi",
  },
  {
    Name: "Xayah",
    Key_region: "Ionia",
    Adaptive_type: "physical",
    Sex: "female",
    Typical_lane: "Bottom",
    Typical_lane_two: "None",
    Class: "Marksman",
    Resource_type: "Mana",
    Race: "Vastaya",
    Faction: "the Vastaya",
    Key_Character_rel: "Rakan",
  },
  {
    Name: "Xerath",
    Key_region: "Shurima",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Mid",
    Typical_lane_two: "Support",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Baccai",
    Faction: "None",
    Key_Character_rel: "Azir",
  },
  {
    Name: "Xin Zhao",
    Key_region: "Demacia",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Jungle",
    Typical_lane_two: "None",
    Class: "Fighter",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "the Lightshield House",
    Key_Character_rel: "Jarvan IV",
  },
  {
    Name: "Yasuo",
    Key_region: "Ionia",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Mid",
    Typical_lane_two: "Top",
    Class: "Fighter",
    Resource_type: "Flow",
    Race: "Human",
    Faction: "None",
    Key_Character_rel: "Yone",
  },
  {
    Name: "Yone",
    Key_region: "Ionia",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Mid",
    Typical_lane_two: "Top",
    Class: "Fighter",
    Resource_type: "None",
    Race: "Human",
    Faction: "None",
    Key_Character_rel: "Yasuo",
  },
  {
    Name: "Yorick",
    Key_region: "Shadow Isles",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Top",
    Typical_lane_two: "None",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "None",
    Key_Character_rel: "Hecarim",
  },
  {
    Name: "Yuumi",
    Key_region: "Bandle City",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Support",
    Typical_lane_two: "None",
    Class: "Multi-class",
    Resource_type: "Mana",
    Race: "Cat",
    Faction: "None",
    Key_Character_rel: "Tristana",
  },
  {
    Name: "Zac",
    Key_region: "Zaun",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Jungle",
    Typical_lane_two: "Top",
    Class: "Multi-class",
    Resource_type: "Health",
    Race: "Golem",
    Faction: "None",
    Key_Character_rel: "Twitch",
  },
  {
    Name: "Zed",
    Key_region: "Ionia",
    Adaptive_type: "physical",
    Sex: "male",
    Typical_lane: "Mid",
    Typical_lane_two: "Jungle",
    Class: "Assassin",
    Resource_type: "Energy",
    Race: "Human",
    Faction: "the Shadow Order",
    Key_Character_rel: "Shen",
  },
  {
    Name: "Zeri",
    Key_region: "Zaun",
    Adaptive_type: "physical",
    Sex: "female",
    Typical_lane: "Bottom",
    Typical_lane_two: "None",
    Class: "Marksman",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "None",
    Key_Character_rel: "Ekko",
  },
  {
    Name: "Ziggs",
    Key_region: "Bandle City",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Mid",
    Typical_lane_two: "Bottom",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Yordle",
    Faction: "None",
    Key_Character_rel: "Heimerdinger",
  },
  {
    Name: "Zilean",
    Key_region: "Icathia",
    Adaptive_type: "magical",
    Sex: "male",
    Typical_lane: "Support",
    Typical_lane_two: "Mid",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Human",
    Faction: "None",
    Key_Character_rel: "Jax",
  },
  {
    Name: "Zoe",
    Key_region: "Targon",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Mid",
    Typical_lane_two: "None",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Aspect Host",
    Faction: "the Rakkor",
    Key_Character_rel: "Leona",
  },
  {
    Name: "Zyra",
    Key_region: "Ixtal",
    Adaptive_type: "magical",
    Sex: "female",
    Typical_lane: "Support",
    Typical_lane_two: "None",
    Class: "Mage",
    Resource_type: "Mana",
    Race: "Unknown",
    Faction: "None",
    Key_Character_rel: "Ivern",
  },
];

/*
export { questionDatabase };

function createQuestionDatabase() {
  let championSorted = championDatabase.sort(() => Math.random() - 0.5); // this is the key
  let questionRegion = championSorted[0].Key_region;
  let questionAttackType = championSorted[0].Adaptive_type;
  let questionSex = championSorted[0].Sex;
  let questionTypicalLane = championSorted[0].Typical_lane;
  let questionClass = championSorted[0].Class;
  let questionResource = championSorted[0].Resource_type;
  let questionRace = championSorted[0].Race;
  let questionFaction = championSorted[0].Faction;
  let questionCharRel = championSorted[0].Key_Character_rel;

  let questionDatabase = [
    {
      questionOne: `Does your champion have anything to do with ${questionRegion}?`,
    },
    {
      questionOne: `Is your champion's primary source of damage ${questionAttackType.toLowerCase()}?`,
    },
    {
      questionOne: `Is your champion ${questionSex.toLowerCase()}?`,
    },
    {
      questionOne: `Does your champion get commonly played in ${questionTypicalLane.toLowerCase()}?`,
    },
    {
      questionOne: `Is your champion a ${questionClass.toLowerCase()} champion?`,
    },
    {
      questionOne: `Does your champion use ${questionResource.toLowerCase()}?`,
    },
    {
      questionOne: `Is your champion a ${questionRace}?`,
    },
    {
      questionOne: `Is your champion affiliated with ${questionFaction}?`,
    },
    {
      questionOne: `Does your character have anything in common with ${questionCharRel}?`,
    },
  ];
}
*/
